blank_issues_enabled: false
contact_links:
  - name: Looking Glass on Level1Tech's Forum
    url: https://forum.level1techs.com/c/software/lookingGlass/142
    about: Ask for help by creating a New Topic on the Level1Tech's forum
  - name: Looking Glass Discord Server
    url: https://discord.gg/52SMupxkvt
    about: Ask for help in the Looking Glass discord server

