#!/usr/bin/env bash
vm="win11"

if [ "$(virsh -c qemu:///system domstate "$vm" 2>/dev/null)" != "running" ]; then
    virsh -c qemu:///system start "$vm" >/dev/null 2>&1 &
fi

exec "${BASH_SOURCE%/*}/looking-glass-client.bin" "$@" 2>/dev/null || \
exec looking-glass-client.bin "$@"
